Ensure SUDO_USER a member of the libvirt group
so that the minikube start command works (with this current setup fo tube-start.sh)

when user not in the group, after rebooting and running the minikube start command, they will receive the following message:
'kvm2' driver reported an issue: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

IF this occurs, the only way to resolve is minikube delete, and to add the suer to the libvirt group command before trying again.